import type { Metadata } from "next";
import "./globals.css";
import Snackbar from "@/ui/Snackbar";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {children}
          <Snackbar />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
